version: "3.7"

services:
  keycloak:
    restart: always
    container_name: keycloak
    image: jboss/keycloak:6.0.1
    ports:
      - "3030:3030"
    environment:
      - KEYCLOAK_USER=l3keycloakadmin
      - KEYCLOAK_PASSWORD=L3Keyclo@k@dmin1209
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/samplerealm.json
    command:
      - "-b 0.0.0.0"
    volumes:
      - "./samplerealm.json:/opt/jboss/keycloak/samplerealm.json"
